Initial testing of -fno-resolve flag works. Next step is to make this work with CVEAssert instrumentation.

diff --git a/resolve-cveassert/bin/resolvecc b/resolve-cveassert/bin/resolvecc
--- a/resolve-cveassert/bin/resolvecc
+++ b/resolve-cveassert/bin/resolvecc
@@ -14,6 +14,15 @@ SCRIPT_DIR="${0%/*}"
 REAL_CLANG="/usr/bin/clang"
 LIB_DIR="$SCRIPT_DIR"/../lib
 
+# Path to fact-gen plugin
+FACT_PLUGIN="$LIB_DIR"/libResolveFactsPlugin.so
+
+# Variable tells resolvecc whether to link libresolve or not
+LINK_LIBRESOLVE=true
+
+# Variable tells resolvecc to include fact-gen plugin
+USE_RESOLVE=true
+
 # DEBUGGING: Writes each compiler invocation to stderr 
 echo "[resolvecc] $@" >&2
 
@@ -21,17 +30,21 @@ echo "[resolvecc] $@" >&2
 # for optimization we want our CVEAssert sanitizers to see the original libc
 # functions, so we ask clang to skip the special handling
 # Ideally, we would only do that for vulnerable functions, but that requires behavior changes in clang or modifying source code
-COMPTIME_FLAGS=(
-    -fno-builtin-memcpy
-    -fno-builtin-memmove
-    -fno-builtin-memset
-    -fpass-plugin="$LIB_DIR"/libCVEAssert.so
-)
+# COMPTIME_FLAGS=(
+#     -fno-builtin-memcpy
+#     -fno-builtin-memmove
+#     -fno-builtin-memset
+#     -fpass-plugin="$LIB_DIR"/libCVEAssert.so
+# )
 
-RUNTIME_FLAGS=(
-    -L"$LIB_DIR"
-    -lresolve
-    -Wl,-rpath="$LIB_DIR"
+# RUNTIME_FLAGS=(
+#     -L"$LIB_DIR"
+#     -lresolve
+#     -Wl,-rpath="$LIB_DIR"
+# )
+
+COMPTIME_FLAGS=(
+    "-fpass-plugin=$FACT_PLUGIN"
 )
 
 
@@ -73,14 +86,11 @@ All other options are forwarded directly to clang.
 EXAMPLES:
     resolvecc -fcve-assert vuln.json test.c
     resolvecc -fcve-assert vuln.json -lresolve -O2 -g test.c
+    resolvecc -fno-resolve test.c 
     resolvecc -c test.c
 EOF
     exit 0
 fi
-
-# Variable tells resolvecc whether to link libresolve or not
-LINK_LIBRESOLVE=true
-
 
 # resolvecc -fcve-assert=<vuln.json> <flags> <source>
 RESOLVE_LABEL_CVE=""
@@ -91,33 +101,50 @@ for ((i=0; i<${#args[@]}; i++)); do
     
     arg="${args[$i]}"
 
-    if [[ "$arg" == "-c" || "$arg" == "-S" || "$arg" == "-E" ]]; then
-        LINK_LIBRESOLVE=false
+    if [[ "$arg" == "-fno-resolve" ]]; then
+        USE_RESOLVE=false
+        continue
     fi
 
-    if [[ "$arg" == "-fcve-assert" ]]; then
-        file_path="${args[$((i + 1))]}"
-        if [[ ! -f "$file_path" ]]; then
-            echo "[resolvecc]: ERROR '$file_path' could not be found!"
-            exit 1
-        fi 
+    NEW_ARGS+=("$arg")
 
-        RESOLVE_LABEL_CVE="$file_path"
-        i=$((i + 2)) # Skip over flag and file path, clang does not understand these flags. 
-    else 
-        NEW_ARGS+=("$arg")
-    fi
+    # if [[ "$arg" == "-c" || "$arg" == "-S" || "$arg" == "-E" ]]; then
+    #     LINK_LIBRESOLVE=false
+    # fi
+    # if [[ "$arg" == "-fcve-assert" ]]; then
+    #     file_path="${args[$((i + 1))]}"
+    #     if [[ ! -f "$file_path" ]]; then
+    #         echo "[resolvecc]: ERROR '$file_path' could not be found!"
+    #         exit 1
+    #     fi 
+
+    #     RESOLVE_LABEL_CVE="$file_path"
+    #     i=$((i + 2)) # Skip over flag and file path, clang does not understand these flags. 
+    # else 
+    #     NEW_ARGS+=("$arg")
+    # fi
 done 
 
-if $LINKING; then
-    RESOLVE_LABEL_CVE="$RESOLVE_LABEL_CVE"\
-    exec "$REAL_CLANG" \
-        "${COMPTIME_FLAGS[@]}" \
-        "${NEW_ARGS[@]}" \
-        "${RUNTIME_FLAGS[@]}"
-else 
-    RESOLVE_LABEL_CVE="$RESOLVE_LABEL_CVE"\
+if $USE_RESOLVE; then 
     exec "$REAL_CLANG" \
         "${COMPTIME_FLAGS[@]}" \
         "${NEW_ARGS[@]}"
+
+
+else
+    exec "$REAL_CLANG" \
+        "${NEW_ARGS[@]}"
 fi
+
+# if $LINKING; then
+#     RESOLVE_LABEL_CVE="$RESOLVE_LABEL_CVE"\
+#     exec "$REAL_CLANG" \
+#         "${COMPTIME_FLAGS[@]}" \
+#         "${NEW_ARGS[@]}" \
+#         "${RUNTIME_FLAGS[@]}"
+# else 
+#     RESOLVE_LABEL_CVE="$RESOLVE_LABEL_CVE"\
+#     exec "$REAL_CLANG" \
+#         "${COMPTIME_FLAGS[@]}" \
+#         "${NEW_ARGS[@]}"
+# fi
